"""empty message

Revision ID: cb51e628abb8
Revises: 44030f912254
Create Date: 2020-08-23 03:04:06.311742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb51e628abb8'
down_revision = '44030f912254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['facebook_link'])
    op.create_unique_constraint(None, 'venues', ['facebook_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
